"""Agregar campos para registrar entrada, salida, desayuno y almuerzo en Turno

Revision ID: cb4d9b920495
Revises: 
Create Date: 2024-09-13 18:38:17.161384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb4d9b920495'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registro_turno')
    with op.batch_alter_table('turno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hora_entrada', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('hora_salida', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('hora_desayuno', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('hora_almuerzo', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turno', schema=None) as batch_op:
        batch_op.drop_column('hora_almuerzo')
        batch_op.drop_column('hora_desayuno')
        batch_op.drop_column('hora_salida')
        batch_op.drop_column('hora_entrada')

    op.create_table('registro_turno',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('agente_id', sa.INTEGER(), nullable=False),
    sa.Column('fecha', sa.DATE(), nullable=False),
    sa.Column('hora_entrada', sa.TIME(), nullable=True),
    sa.Column('hora_salida', sa.TIME(), nullable=True),
    sa.Column('hora_desayuno', sa.TIME(), nullable=True),
    sa.Column('hora_almuerzo', sa.TIME(), nullable=True),
    sa.ForeignKeyConstraint(['agente_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
